module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'index',
        'features',
        'main/getting-started/overview',
        'main/getting-started/requirements',
        'main/getting-started/choosing-os',
        'main/getting-started/faqs'
      ],
    },
    {
      type: 'category',
      label: 'Customization',
      collapsed: false,
      items: [
        'main/customization/index',
        'main/customization/software',
        'main/customization/scripting',
        'main/customization/secrets',
        'main/customization/web-apps',
        'main/customization/sso'
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      collapsed: false,
      items: [
        'main/advanced/installer',
        'main/advanced/security',
        'main/advanced/network',
        'main/advanced/virtualization',
        'main/advanced/qubes'
      ],
    },
    {
      type: 'category',
      label: 'Enterprise',
      collapsed: true,
      items: [
        'main/enterprise/index',
        'main/enterprise/immutable',
        'main/enterprise/portal'
      ]
    },
    {
      type: 'category',
      label: 'Contributing',
      collapsed: true,
      items: [
        'main/contributing/index',
        'main/contributing/code-quality',
        'main/contributing/pull-requests',
        'main/contributing/feature-requests',
        'main/contributing/documentation',
        'main/contributing/community-guidelines'
      ],
    },
  ],

  api: [
    {
      type: 'category',
      label: 'Software',
      collapsed: false,
      items: ['software', 'software/package-explorer', 'software/scripts'],
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsed: false,
      items: ['integrations', 'integrations/cloudflare', 'integrations/kubesphere', 'integrations/tailscale', 'integrations/netdata', 'integrations/gitsync'],
    },
  ],
  cli: [
    {
      type: 'category',
      label: 'CLI Documentation',
      collapsed: false,
      items: ['cli/index', 'cli/taskfiles'],
    },
    {
      type: 'category',
      label: 'Command Reference',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'cli/commands', // Generate section automatically based on files
        },
      ],
    },
  ],
};
